### ISSUE TITLE
更换execjs环境

### ISSUE THREAD

**Issue by feifanhanmc** [ziliwang/GoogleFreeTrans#2]
在ubuntu上试了一下，报错提示(-6, '', 'QXcbConnection: Could not connect to display \nPhantomJS has crashed. Please read the bug reporting guide at\n<http://phantomjs.org/bug-reporting.html> and file a bug report.\n'
然后参考[python运行js](https://www.jianshu.com/p/e01a3d504700)
以及[Node.js 安装配置](http://www.runoob.com/nodejs/nodejs-install-setup.html)
配置环境`os.environ["EXECJS_RUNTIME"] = "Node"`
再使用就ok了

另外您的测试用例里面
translator = Translator.translator(src='en', dest='fr')
好像把src误写成scr了XD

**Comment by ziliwang** [comment]
谢谢，已修改
